import Vue from "vue";
import {
  Button,
  Row,
  Col,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Input,
  Popover,
  Carousel,
  CarouselItem,
  Pagination,
  Switch,
  Autocomplete,
  Form,
  FormItem,
  Select,
  Option,
  DatePicker,
  TimePicker,
  CheckboxGroup,
  Checkbox,
  Radio,
  RadioGroup,
  Dialog,
  Divider,
  TableColumn,
  Table,
  MessageBox,
  Rate,
  Calendar,
  InputNumber,
} from "element-ui";

Vue.use(Button);
Vue.use(Row);
Vue.use(Col);
Vue.use(Container);
Vue.use(Header);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Footer);
Vue.use(Input);
Vue.use(Popover);
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Pagination);
Vue.use(Switch);
Vue.use(Autocomplete);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Select);
Vue.use(Option);
Vue.use(DatePicker);
Vue.use(TimePicker);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Dialog);
Vue.use(Divider);
Vue.use(TableColumn);
Vue.use(Table);
Vue.prototype.$msgbox = MessageBox;
Vue.use(Rate);
Vue.use(Calendar);
Vue.use(InputNumber);
